repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.94.1
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_validate
        args:
          - --args=-json
          - --args=-no-color
          - --hook-config=--retry-once-with-cleanup=true
      - id: terraform_trivy
        args:
          - --args=--skip-dirs="**/.terraform"
          - --args=--ignorefile=__GIT_WORKING_DIR__/.trivyignore
