/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const ApplicationInfoR = t.interface({
  name: t.string,

  version: t.string
});

// optional attributes
const ApplicationInfoO = t.partial({});

export const ApplicationInfo = t.intersection(
  [ApplicationInfoR, ApplicationInfoO],
  "ApplicationInfo"
);

export type ApplicationInfo = t.TypeOf<typeof ApplicationInfo>;
