/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { UnlockCode } from "./UnlockCode";
import * as t from "io-ts";

// required attributes
const AuthLockBodyR = t.interface({
  unlock_code: UnlockCode
});

// optional attributes
const AuthLockBodyO = t.partial({});

export const AuthLockBody = t.intersection(
  [AuthLockBodyR, AuthLockBodyO],
  "AuthLockBody"
);

export type AuthLockBody = t.TypeOf<typeof AuthLockBody>;
