/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const UserSessionInfoR = t.interface({
  active: t.boolean
});

// optional attributes
const UserSessionInfoO = t.partial({});

export const UserSessionInfo = t.intersection(
  [UserSessionInfoR, UserSessionInfoO],
  "UserSessionInfo"
);

export type UserSessionInfo = t.TypeOf<typeof UserSessionInfo>;
