/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { UnlockCode } from "./UnlockCode";
import * as t from "io-ts";

// required attributes
const AuthUnlockBodyR = t.interface({});

// optional attributes
const AuthUnlockBodyO = t.partial({
  unlock_code: UnlockCode
});

export const AuthUnlockBody = t.intersection(
  [AuthUnlockBodyR, AuthUnlockBodyO],
  "AuthUnlockBody"
);

export type AuthUnlockBody = t.TypeOf<typeof AuthUnlockBody>;
