/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { SessionInfo } from "./SessionInfo";
import * as t from "io-ts";

/**
 * The state of the user' session
 */

// required attributes
const SessionStateR = t.interface({
  access_enabled: t.boolean,

  session_info: SessionInfo
});

// optional attributes
const SessionStateO = t.partial({});

export const SessionState = t.intersection(
  [SessionStateR, SessionStateO],
  "SessionState"
);

export type SessionState = t.TypeOf<typeof SessionState>;
