/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */

import * as t from "io-ts";

// required attributes
const SuccessResponseR = t.interface({});

// optional attributes
const SuccessResponseO = t.partial({
  message: t.string
});

export const SuccessResponse = t.intersection(
  [SuccessResponseR, SuccessResponseO],
  "SuccessResponse"
);

export type SuccessResponse = t.TypeOf<typeof SuccessResponse>;
