/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { PatternString } from "@pagopa/ts-commons/lib/strings";
import * as t from "io-ts";

export type UnlockCode = t.TypeOf<typeof UnlockCode>;
export const UnlockCode = PatternString("^\\d{9}$");
