/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import { SessionInfo } from "./SessionInfo";
import * as t from "io-ts";

/**
 * Contains all active sessions for an authenticated user.
 */

// required attributes
const SessionsListR = t.interface({
  sessions: t.readonlyArray(SessionInfo, "array of SessionInfo")
});

// optional attributes
const SessionsListO = t.partial({});

export const SessionsList = t.exact(
  t.intersection([SessionsListR, SessionsListO], "SessionsList")
);

export type SessionsList = t.TypeOf<typeof SessionsList>;
