/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import * as t from "io-ts";

// required attributes
const UserMetadataR = t.interface({
  version: t.number,

  metadata: t.string
});

// optional attributes
const UserMetadataO = t.partial({});

export const UserMetadata = t.exact(
  t.intersection([UserMetadataR, UserMetadataO], "UserMetadata")
);

export type UserMetadata = t.TypeOf<typeof UserMetadata>;
