/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/pagopa/italia-utils
 */
/* eslint-disable  */

import {
  RequestParams,
  TypeofApiCall,
  createFetchRequestForApi,
  ReplaceRequestParams,
  ApiHeaderJson,
  TypeofApiParams
} from "@pagopa/ts-commons/lib/requests";

import {
  LockUserSessionT,
  lockUserSessionDefaultDecoder,
  UnlockUserSessionT,
  unlockUserSessionDefaultDecoder
} from "@pagopa/io-backend-session-sdk/requestTypes";
import { identity } from "fp-ts/lib/function";

// This is a placeholder for undefined when dealing with object keys
// Typescript doesn't perform well when narrowing a union type which includes string and undefined
// (example: "foo" | "bar" | undefined)
// We use this as a placeholder for type parameters indicating "no key"
type __UNDEFINED_KEY = "_____";

export type ApiOperation = TypeofApiCall<LockUserSessionT> &
  TypeofApiCall<UnlockUserSessionT>;

export type ParamKeys = keyof (TypeofApiParams<LockUserSessionT> &
  TypeofApiParams<UnlockUserSessionT>);

/**
 * Defines an adapter for TypeofApiCall which omit one or more parameters in the signature
 * @param ApiT the type which defines the operation to expose
 * @param K the parameter to omit. undefined means no parameters will be omitted
 */
export type OmitApiCallParams<
  ApiT,
  K extends ParamKeys | undefined = undefined
> = (
  op: TypeofApiCall<ApiT>
) => K extends string
  ? TypeofApiCall<ReplaceRequestParams<ApiT, Omit<RequestParams<ApiT>, K>>>
  : TypeofApiCall<ApiT>;

/**
 * Defines an adapter for TypeofApiCall which omit one or more parameters in the signature
 * @param ApiT the type which defines the operation to expose
 * @param K the parameter to omit. undefined means no parameters will be omitted
 */
export type WithDefaultsT<
  K extends ParamKeys | undefined = undefined
> = OmitApiCallParams<LockUserSessionT | UnlockUserSessionT, K>;

/**
 * Defines a collection of api operations
 * @param K name of the parameters that the Clients masks from the operations
 */
export type Client<K extends ParamKeys | __UNDEFINED_KEY = __UNDEFINED_KEY> = {
  readonly lockUserSession: TypeofApiCall<
    ReplaceRequestParams<
      LockUserSessionT,
      Omit<RequestParams<LockUserSessionT>, K>
    >
  >;

  readonly unlockUserSession: TypeofApiCall<
    ReplaceRequestParams<
      UnlockUserSessionT,
      Omit<RequestParams<UnlockUserSessionT>, K>
    >
  >;
};

// TODO(IOPID-1648): Move to generated client

/**
 * Create an instance of a client
 * @param params hash map of parameters thata define the client:
 *  - baseUrl: the base url for every api call (required)
 *  - fetchApi: an implementation of the fetch() web API, depending on the platform (required)
 *  - basePath: optional path to be appended to the baseUrl
 *  - withDefaults: optional adapter to be applied to every operation, to omit some paramenters
 * @returns a collection of api operations
 */
export function createClient<K extends ParamKeys>(params: {
  baseUrl: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  fetchApi: typeof fetch;
  withDefaults: WithDefaultsT<K>;
  basePath?: string;
}): Client<K>;
export function createClient(params: {
  baseUrl: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  fetchApi: typeof fetch;
  withDefaults?: undefined;
  basePath?: string;
}): Client;
export function createClient<K extends ParamKeys>({
  baseUrl,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  fetchApi,
  withDefaults,
  basePath = "/api/v1"
}: {
  baseUrl: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  fetchApi: typeof fetch;
  withDefaults?: WithDefaultsT<K>;

  basePath?: string;
}) {
  const options = {
    baseUrl,
    fetchApi
  };

  const lockUserSessionT: ReplaceRequestParams<
    LockUserSessionT,
    RequestParams<LockUserSessionT>
  > = {
    method: "post",

    headers: ApiHeaderJson,

    response_decoder: lockUserSessionDefaultDecoder(),
    url: ({ fiscalcode }) => `${basePath}/sessions/${fiscalcode}/lock`,

    body: () => "{}",

    query: ({ token }) => ({ token })
  };
  const lockUserSession = (withDefaults || identity)(
    createFetchRequestForApi(lockUserSessionT, options)
  );

  const unlockUserSessionT: ReplaceRequestParams<
    UnlockUserSessionT,
    RequestParams<UnlockUserSessionT>
  > = {
    method: "delete",

    headers: ApiHeaderJson,

    response_decoder: unlockUserSessionDefaultDecoder(),
    url: ({ fiscalcode }) => `${basePath}/sessions/${fiscalcode}/lock`,

    query: ({ token }) => ({ token })
  };
  const unlockUserSession = (withDefaults || identity)(
    createFetchRequestForApi(unlockUserSessionT, options)
  );

  return {
    lockUserSession,
    unlockUserSession
  };
}
