name: Code Deploy - PROD

on:
  workflow_dispatch:
      
jobs:
  deploy_on_prod:
    uses: ./.github/workflows/cd_code_deploy.yaml
    name: Deploy on PROD
    secrets: inherit
    with:
      environment: 'prod'
      resource_group_name: 'io-p-admin-rg'
      app_name: 'io-p-admin-fn'
      use_staging_slot: true
      use_private_agent: false
