name: PR - Code Review

on:
  workflow_dispatch:
  push:
    branches:
      - EC-337-functions-cicd-pipelines
  # pull_request:
  #   types:
  #     - opened
  #     - edited
  #     - synchronize
  #     - reopened
  #     - ready_for_review
  #   paths:
  #     - "src/domains/functions**"
  #     - ".github/workflows/functions**.yml"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      name: Checkout

    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version-file: ".node-version"
        cache: "yarn"

    # - name: Install dependencies
    #   run: yarn install --immutable

    - name: Build
      run: yarn build

  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      name: Checkout

    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version-file: ".node-version"
        cache: "yarn"
        
    # - name: Install dependencies
    #   run: yarn install --immutable

    - name: Lint
      run: yarn lint

    - name: Lint API
      run: yarn lint-api

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      name: Checkout

    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version-file: ".node-version"
        cache: "yarn"
        
    # - name: Install dependencies
    #   run: yarn install --immutable

    - name: Generate definitions
      run: yarn generate

    - name: Run unit tests
      run: yarn test:coverage

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)