name: Code Review

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "*"
      - "!infra/*"
      - "!.github/*"
  push:
    branches:
      - EC-337-functions-cicd-pipelines

jobs:
  deploy_on_prod:
    uses: pagopa/dx/.github/workflows/legacy_code_review.yaml@workflow-functions-test
    name: Code Review
    secrets: inherit