name: Publish SDK - PROD

on:
  workflow_dispatch:
  push:
    branches:
      - EC-337-functions-cicd-pipelines
      
jobs:
  deploy_on_prod:
    uses: pagopa/dx/.github/workflows/legacy_publish_sdk.yaml@workflow-functions-test
    name: Publish SDK on PROD
    secrets: inherit
    with:
      environment: 'prod'
      use_private_agent: false
      openapiSpecPath: openapi/index.yaml
